[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "optionspricer"
version = "0.1"
dependencies = [
    "numpy",
    "scipy"
]

[tool.hatch.build.targets.wheel]
packages = [
    "optionspricer"
]